name: macOS
on:
  push:
  pull_request:
jobs:
  macOS-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-11]
    steps:
    - uses: actions/checkout@v2
    - name: Install Fuse-t
      run: |
       brew tap macos-fuse-t/homebrew-cask
       wget -q https://github.com/macos-fuse-t/fuse-t/releases/download/1.0.36/fuse-t-macos-installer-1.0.36.pkg
       sudo installer -pkg fuse-t-macos-installer-1.0.36.pkg -target /
    - name: Install CernVM-FS
      run: |
       wget -q http://ecsft.cern.ch/dist/cvmfs/nightlies/cvmfs-git-1234/cvmfs-2.12.0-0.1234-git-958741c6df468802.pkg
       sudo installer -pkg cvmfs-2.12.0-0.1234-git-958741c6df468802.pkg -target /
       sudo sh -c 'echo "CVMFS_CLIENT_PROFILE=single" > /etc/cvmfs/default.local '
       sudo sh -c 'echo "CVMFS_REPOSITORIES=sft.cern.ch" >> /etc/cvmfs/default.local '
       sudo sh -c 'echo "CVMFS_HTTP_PROXY=DIRECT" >> /etc/cvmfs/default.local '
       sudo sh -c 'echo "CVMFS_MOUNT_DIR=/tmp/cvmfs" >> /etc/cvmfs/default.local '

       sudo cvmfs_config setup
       for repo in $(echo cvmfs-config.cern.ch,sft.cern.ch | sed "s/,/ /g")
       do
         mkdir -p /Users/Shared/cvmfs/${repo}
         sudo mount -t cvmfs ${repo} /Users/Shared/cvmfs/${repo}
       done
       ls -alh /Users/Shared/cvmfs/cvmfs-config.cern.ch/etc
       ls -alh /Users/Shared/cvmfs/sft.cern.ch/lcg
       sudo zsh -c 'echo -e "cvmfs\tUsers/Shared/cvmfs\n#comment\n" > /etc/synthetic.conf'
       cat /etc/synthetic.conf
       sudo chown root:wheel /etc/synthetic.conf
       sudo chmod a+r /etc/synthetic.conf
       sudo /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t || true
       ls /cvmfs
       ls /cvmfs/sft.cern.ch


