name: macOS
on:
  push:
  pull_request:
jobs:
  macOS-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-10.15, macos-11]
    steps:
    - uses: actions/checkout@v2
    - uses: Homebrew/actions/setup-homebrew@master
    - name: Test CernVM-FS
      run: |
       brew tap macos-fuse-t/homebrew-cask
       brew install fuse-t
       brew install fuse-t-sshfs
