name: macOS
on:
  push:
  pull_request:
jobs:
  macOS-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-11]
    steps:
    - uses: actions/checkout@v2
    - uses: Homebrew/actions/setup-homebrew@master
    - name: Install Fuse-t
      run: |
       brew tap macos-fuse-t/homebrew-cask
       brew install fuse-t
    - name: Install CernVM-FS
      run: |
       wget -q http://ecsft.cern.ch/dist/cvmfs/nightlies/cvmfs-git-1234/cvmfs-2.12.0-0.1234-git-958741c6df468802.pkg
       sudo installer -pkg cvmfs-2.12.0-0.1234-git-958741c6df468802.pkg -target /
       sudo cvmfs_config setup
       sudo sh -c 'echo "CVMFS_CLIENT_PROFILE=single" > /etc/cvmfs/default.local '
       sudo sh -c 'echo "CVMFS_REPOSITORIES=sft.cern.ch" >> /etc/cvmfs/default.local '
       sudo sh -c 'echo "CVMFS_HTTP_PROXY=DIRECT" >> /etc/cvmfs/default.local '
       sudo cvmfs_config chksetup
       sudo cvmfs_config probe


