name: macOS
on:
  push:
  pull_request:
jobs:
  macOS-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-11]
    steps:
    - uses: actions/checkout@v2
    - uses: Homebrew/actions/setup-homebrew@master
    - name: Install Fuse-t
      run: |
       brew tap macos-fuse-t/homebrew-cask
       brew install fuse-t
    - name: Build CernVM-FS
      run: |
       sudo -H pip install setuptools
       git clone --depth 1 -b mac-fuse-t https://github.com/cvmfs/cvmfs
       cd cvmfs
       ./ci/cvmfs/pkg.sh $PWD $PWD/build 1234 
    - uses: actions/upload-artifact@v4
      with:
      path: /Users/runner/work/cvm-gh-ci/cvm-gh-ci/cvmfs/build/pkg_result/cvmfs*.pkg
